"""
Django settings for portfoliov2 project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read SECRET_KEY from the environment in production; fall back to the local value for
# development only.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-qay+4_y#*vq$j%w*=w5@&ch$_#9kb)t+2*!4$224)=^!jdwcwv",
)

# SECURITY WARNING: don't run with debug turned on in production!
import os

# SECURITY WARNING: don't run with debug turned on in production!
# Use the DJANGO_DEBUG env var on the host (set to 'False' in production).
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# Allowed hosts control which host/domain names this Django site can serve.
# In production add your PythonAnywhere domain (and any custom domains).
# You can set ALLOWED_HOSTS via the ALLOWED_HOSTS env var (comma-separated),
# or it will default to the PythonAnywhere domain plus localhost.
ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "aadityaanand.pythonanywhere.com,localhost,127.0.0.1",
).split(",")

# Database configuration: use DATABASE_URL when provided (Railway/Postgres).
try:
    import dj_database_url

    DATABASE_URL = os.environ.get("DATABASE_URL")
    if DATABASE_URL:
        DATABASES = {"default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)}
except Exception:
    # dj-database-url is optional; if it's not installed or DATABASE_URL not set, keep
    # the default sqlite configuration above.
    pass


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core.apps.CoreConfig",
    ]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise should come directly after SecurityMiddleware to serve static files
    # efficiently in production when using gunicorn.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "portfoliov2.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "portfoliov2.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise static file optimization: use compressed manifest storage so files are
# cached aggressively and URLs include a hash for cache-busting.
try:
    # Django 5 supports STORAGES; override staticfiles backend when whitenoise is present.
    from whitenoise.storage import CompressedManifestStaticFilesStorage  # noqa: F401
    STORAGES = globals().get('STORAGES', {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    })
    STORAGES['staticfiles']['BACKEND'] = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
except Exception:
    # If whitenoise not available during a build step, fall back silently.
    pass

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
